# SPOTIFY CLIENT AND SECRET
# This allows the program to use different spotify credential(s) to query spotify playlists using these credentials.
#
# The key of the dictionary must match the person's name used for training the face
# recognition algorithm. The config below is valid if your model was trained to detect
# "alice" and "bob".

SECRET:
    alice: 
      client_id: alice-spotify-client-id
      client_secret: alice-spotify-client-secret
    bob: 
      client_id: bob-spotify-client-id
      client_secret: bob-spotify-client-secret

# SPOTIFY PLAYLIST URI
# Upon recognizing the face of these user, the program will play these spotify playlist.
# You can obtain a spotify playlist's URI by right-clicking a playlist and selecting: "Share --> Copy spotify URI"

PLAYLIST:
  alice: spotify:playlist:alice
  bob: spotify:playlist:bob

# PARAMETERS FOR PLAYING A LOCAL SONG
# As an alternative to playing your spotify music, people's anthem can play a local song
PEOPLE_SONG:
  alice: /home/pi/Music/alice.mp3
  bob: /home/pi/Music/bob.mp3
